version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.1
    - 18.5.2
  - dependency-name: hosted-git-info
    versions:
    - 3.0.8
    - 4.0.0
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  commit-message:
    prefix: chore
    include: scope
  registries:
  - npm-registry-registry-npmjs-org
